"""empty message

Revision ID: f63b7ee426f4
Revises: 0b0d9774df6e
Create Date: 2018-05-21 19:52:17.057960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63b7ee426f4'
down_revision = '0b0d9774df6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
